# Importing required libraries
from config import get_groq_api_key
import pandas as pd
from pydantic import BaseModel
from typing import List, Optional
from groq import Groq
import json
import re

# Function definitions stay at the top
class LabTest(BaseModel):
    test_name: str
    value: float
    unit: Optional[str]
    reference_range: Optional[str]

class LabReport(BaseModel):
    tests: List[LabTest]

# Generates LLM Responses
def run_llm(raw_text: str):
    """
    Calls Groq LLM with the prompt and returns raw LLM response.
    """
    PROMPT = f"""
    You are a medical data extraction assistant.

    Extract lab test results from the text below.

    Rules:
    - Extract only lab tests
    - Ignore explanations or notes
    - Convert values to numbers
    - Return JSON only

    Format:
    {{
      "tests": [
        {{
          "test_name": "",
          "value": 0,
          "unit": "",
          "reference_range": ""
        }}
      ]
    }}

    Text:
    {raw_text}
    """

    api_key = get_groq_api_key()
    client = Groq(api_key=api_key)
    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "user", "content": PROMPT}],
        temperature=0
    )

    raw_llm_response = response.choices[0].message.content
    return raw_llm_response

def clean_llm_json(raw_text: str) -> str:
    """
    Removes markdown code fences and extracts JSON block.
    """
    cleaned = re.sub(r"^```(?:json)?\s*", "", raw_text.strip())
    cleaned = re.sub(r"\s*```$", "", cleaned)
    return cleaned.strip()

def parse_llm_output(raw_text: str):
    cleaned = clean_llm_json(raw_text)
    try:
        return json.loads(cleaned)
    except json.JSONDecodeError as e:
        print("JSON parsing failed.")
        print("Cleaned text was:")
        print(cleaned)
        raise e

def extract_range(reference_range):
    numbers = re.findall(r"\d+\.?\d*", reference_range)
    if len(numbers) == 2:
        return float(numbers[0]), float(numbers[1])
    return None, None

def flag_value(value, lower, upper):
    if value is None or lower is None or upper is None:
        return "unknown"
    if value < lower:
        return "low"
    elif value > upper:
        return "high"
    else:
        return "normal"

def flag_tests(tests):
    flagged = []
    for test in tests:
        value = test.get("value")
        reference_range = test.get("reference_range", "")
        lower, upper = extract_range(reference_range)
        status = flag_value(value, lower, upper)
        test_with_status = {**test, "status": status}
        flagged.append(test_with_status)
    return flagged

# Now wrap all “script” code in main()
def main():
    # Read raw text from file
    with open("raw_text.txt", "r") as f:
        raw_text = f.read()

    # Call the run_llm function to generate raw llm responses
    raw_llm_response = run_llm(raw_text)

    print("RESPONSES GENERATED BY LLM BEFORE ANY STRUCTURING:\n", raw_llm_response)

    # Parse LLM output
    parsed_data = parse_llm_output(raw_llm_response)
    tests = parsed_data["tests"]

    # Flag tests
    flagged_tests = flag_tests(tests)
    abnormal_tests = [t for t in flagged_tests if t['status'] in ('high', 'low')]

    # Print abnormal tests
    print("\nABNORMAL TESTS DETECTED:")
    for test in abnormal_tests:
        print(test)


# Python guard
if __name__ == "__main__":
    main()
